"""Stable message-key catalog for API/client localization."""

from __future__ import annotations

from collections.abc import Mapping

DEFAULT_LOCALE = "de"
FALLBACK_LOCALE = "en"

MESSAGES: Mapping[str, Mapping[str, str]] = {
    "de": {
        "errors.platform.internal": "Es ist ein interner Plattformfehler aufgetreten.",
        "errors.core.authorization.forbidden": "Der Zugriff auf diese Core-Administration ist nicht erlaubt.",
        "errors.core.tenant.not_found": "Mandant nicht gefunden.",
        "errors.core.branch.not_found": "Niederlassung nicht gefunden.",
        "errors.core.mandate.not_found": "Mandat nicht gefunden.",
        "errors.core.tenant_setting.not_found": "Mandanteneinstellung nicht gefunden.",
        "errors.core.tenant.duplicate_code": "Mandantencode existiert bereits.",
        "errors.core.branch.duplicate_code": "Niederlassungscode existiert in diesem Mandanten bereits.",
        "errors.core.mandate.duplicate_code": "Mandatscode existiert in diesem Mandanten bereits.",
        "errors.core.setting.duplicate_key": "Einstellungsschluessel existiert fuer diesen Mandanten bereits.",
        "errors.core.setting.stale_version": "Die Einstellung wurde zwischenzeitlich geaendert.",
        "errors.core.branch.tenant_mismatch": "Die Niederlassung gehoert nicht zum angeforderten Mandanten.",
        "errors.core.mandate.tenant_mismatch": "Das Mandat gehoert nicht zum angeforderten Mandanten.",
        "errors.core.setting.tenant_mismatch": "Die Einstellung gehoert nicht zum angeforderten Mandanten.",
        "errors.core.mandate.invalid_branch_scope": "Die Mandatsniederlassung gehoert nicht zum Mandanten.",
        "errors.core.lifecycle.archived_record": "Archivierte Datensaetze koennen nicht reaktiviert werden.",
        "errors.core.conflict.integrity": "Die Core-Administrationsaenderung verletzt eine Integritaetsregel.",
        "errors.iam.auth.invalid_credentials": "Die Anmeldedaten sind ungueltig.",
        "errors.iam.auth.invalid_access_token": "Das Zugriffstoken ist ungueltig oder abgelaufen.",
        "errors.iam.auth.invalid_refresh_token": "Das Sitzungstoken ist ungueltig oder abgelaufen.",
        "errors.iam.auth.invalid_reset_token": "Das Passwort-Reset-Token ist ungueltig oder abgelaufen.",
        "errors.iam.auth.rate_limited": "Zu viele Anmeldeversuche. Bitte spaeter erneut versuchen.",
        "errors.iam.authorization.permission_denied": "Die benoetigte Berechtigung fehlt fuer diese Aktion.",
        "errors.iam.authorization.scope_denied": "Der Rollen-Scope erlaubt diesen Zugriff nicht.",
        "errors.docs.document.not_found": "Dokument nicht gefunden.",
        "errors.docs.document_type.not_found": "Dokumenttyp nicht gefunden.",
        "errors.docs.document.tenant_mismatch": "Das Dokument gehoert nicht zum angeforderten Mandanten.",
        "errors.docs.document_link.unsupported_owner_type": "Der Dokument-Linktyp wird nicht unterstuetzt.",
        "errors.docs.document_link.owner_not_found": "Das verknuepfte Zielelement wurde nicht gefunden.",
        "errors.docs.document_link.duplicate": "Diese Dokumentverknuepfung existiert bereits.",
        "errors.docs.document_version.invalid_content": "Der Dokumentinhalt ist ungueltig kodiert.",
        "errors.docs.document_version.not_found": "Dokumentversion nicht gefunden.",
        "errors.docs.storage.object_not_found": "Die gespeicherte Dokumentdatei wurde nicht gefunden.",
        "errors.comm.template.not_found": "Nachrichtenvorlage nicht gefunden.",
        "errors.comm.template.language_not_supported": "Die Sprachversion der Nachrichtenvorlage wird nicht unterstuetzt.",
        "errors.comm.message.not_found": "Ausgehende Nachricht nicht gefunden.",
        "errors.comm.attachment.document_not_found": "Angehaengtes Dokument nicht gefunden.",
        "errors.comm.delivery_attempt.recipient_not_found": "Nachrichtenempfaenger nicht gefunden.",
        "errors.comm.render.missing_placeholder": "Zum Rendern der Nachricht fehlen Platzhalterwerte.",
        "errors.info.notice.not_found": "Hinweis nicht gefunden.",
        "errors.info.notice.audience_missing": "Ein veroeffentlichter Hinweis benoetigt mindestens eine Zielgruppe.",
        "errors.info.notice.audience_kind_invalid": "Die Zielgruppenart fuer den Hinweis ist ungueltig.",
        "errors.info.notice.language_not_supported": "Die Hinweissprache wird nicht unterstuetzt.",
        "errors.info.notice_read.not_visible": "Dieser Hinweis ist fuer die aktuelle Rolle nicht sichtbar.",
        "errors.info.notice_read.already_acknowledged": "Der Hinweis wurde bereits bestaetigt.",
        "errors.info.notice_link.duplicate": "Dieser Hinweislink existiert bereits.",
        "errors.integration.endpoint.not_found": "Integrationsendpunkt nicht gefunden.",
        "errors.integration.job.not_found": "Import-/Export-Job nicht gefunden.",
        "errors.integration.outbox.not_found": "Outbox-Ereignis nicht gefunden.",
        "errors.integration.endpoint.duplicate_provider": "Der Provider-Endpunkt existiert bereits fuer diesen Mandanten.",
        "errors.integration.secret.invalid": "Die Integrationskonfiguration konnte nicht gesichert werden.",
        "messages.iam.auth.logout_success": "Die Sitzung wurde erfolgreich beendet.",
        "messages.iam.auth.password_reset_requested":
            "Wenn ein passendes Konto existiert, wurde ein Reset-Vorgang gestartet.",
        "messages.iam.auth.password_reset_confirmed":
            "Das Passwort wurde erfolgreich zurueckgesetzt.",
    },
    "en": {
        "errors.platform.internal": "An internal platform error has occurred.",
        "errors.core.authorization.forbidden": "Access to this core administration action is not allowed.",
        "errors.core.tenant.not_found": "Tenant not found.",
        "errors.core.branch.not_found": "Branch not found.",
        "errors.core.mandate.not_found": "Mandate not found.",
        "errors.core.tenant_setting.not_found": "Tenant setting not found.",
        "errors.core.tenant.duplicate_code": "Tenant code already exists.",
        "errors.core.branch.duplicate_code": "Branch code already exists in this tenant.",
        "errors.core.mandate.duplicate_code": "Mandate code already exists in this tenant.",
        "errors.core.setting.duplicate_key": "Setting key already exists for this tenant.",
        "errors.core.setting.stale_version": "The setting was changed by another update.",
        "errors.core.branch.tenant_mismatch": "The branch does not belong to the requested tenant.",
        "errors.core.mandate.tenant_mismatch": "The mandate does not belong to the requested tenant.",
        "errors.core.setting.tenant_mismatch": "The setting does not belong to the requested tenant.",
        "errors.core.mandate.invalid_branch_scope": "The mandate branch does not belong to the tenant.",
        "errors.core.lifecycle.archived_record": "Archived records cannot be reactivated.",
        "errors.core.conflict.integrity": "The core administration change violates an integrity rule.",
        "errors.iam.auth.invalid_credentials": "The login credentials are invalid.",
        "errors.iam.auth.invalid_access_token": "The access token is invalid or expired.",
        "errors.iam.auth.invalid_refresh_token": "The session token is invalid or expired.",
        "errors.iam.auth.invalid_reset_token": "The password reset token is invalid or expired.",
        "errors.iam.auth.rate_limited": "Too many login attempts. Please try again later.",
        "errors.iam.authorization.permission_denied": "The required permission for this action is missing.",
        "errors.iam.authorization.scope_denied": "The assigned role scope does not allow this access.",
        "errors.docs.document.not_found": "Document not found.",
        "errors.docs.document_type.not_found": "Document type not found.",
        "errors.docs.document.tenant_mismatch": "The document does not belong to the requested tenant.",
        "errors.docs.document_link.unsupported_owner_type": "The document link owner type is not supported.",
        "errors.docs.document_link.owner_not_found": "The linked owner record was not found.",
        "errors.docs.document_link.duplicate": "This document link already exists.",
        "errors.docs.document_version.invalid_content": "The document content encoding is invalid.",
        "errors.docs.document_version.not_found": "Document version not found.",
        "errors.docs.storage.object_not_found": "The stored document file was not found.",
        "errors.comm.template.not_found": "Message template not found.",
        "errors.comm.template.language_not_supported": "The message-template language is not supported.",
        "errors.comm.message.not_found": "Outbound message not found.",
        "errors.comm.attachment.document_not_found": "Attached document not found.",
        "errors.comm.delivery_attempt.recipient_not_found": "Message recipient not found.",
        "errors.comm.render.missing_placeholder": "Placeholder values are missing for message rendering.",
        "errors.info.notice.not_found": "Notice not found.",
        "errors.info.notice.audience_missing": "A published notice requires at least one audience.",
        "errors.info.notice.audience_kind_invalid": "The notice audience kind is invalid.",
        "errors.info.notice.language_not_supported": "The notice language is not supported.",
        "errors.info.notice_read.not_visible": "This notice is not visible for the current role scope.",
        "errors.info.notice_read.already_acknowledged": "The notice has already been acknowledged.",
        "errors.info.notice_link.duplicate": "This curated notice link already exists.",
        "errors.integration.endpoint.not_found": "Integration endpoint not found.",
        "errors.integration.job.not_found": "Import/export job not found.",
        "errors.integration.outbox.not_found": "Outbox event not found.",
        "errors.integration.endpoint.duplicate_provider": "The provider endpoint already exists for this tenant.",
        "errors.integration.secret.invalid": "The integration configuration could not be secured.",
        "messages.iam.auth.logout_success": "The session has been terminated successfully.",
        "messages.iam.auth.password_reset_requested":
            "If a matching account exists, a reset flow has been started.",
        "messages.iam.auth.password_reset_confirmed":
            "The password has been reset successfully.",
    },
}


def translate_message(message_key: str, locale: str = DEFAULT_LOCALE) -> str:
    """Return a localized message for known API message keys."""

    normalized = locale.split("-")[0].lower()
    catalog = MESSAGES.get(normalized, MESSAGES[FALLBACK_LOCALE])
    fallback_catalog = MESSAGES[FALLBACK_LOCALE]
    return catalog.get(message_key) or fallback_catalog.get(message_key) or message_key
