"""Stable message-key catalog for API/client localization."""

from __future__ import annotations

from collections.abc import Mapping

DEFAULT_LOCALE = "de"
FALLBACK_LOCALE = "en"

MESSAGES: Mapping[str, Mapping[str, str]] = {
    "de": {
        "errors.platform.internal": "Es ist ein interner Plattformfehler aufgetreten.",
        "errors.platform.database_unavailable": "Die Datenbank ist aktuell nicht erreichbar.",
        "errors.core.authorization.forbidden": "Der Zugriff auf diese Core-Administration ist nicht erlaubt.",
        "errors.core.tenant.not_found": "Mandant nicht gefunden.",
        "errors.core.branch.not_found": "Niederlassung nicht gefunden.",
        "errors.core.mandate.not_found": "Mandat nicht gefunden.",
        "errors.core.tenant_setting.not_found": "Mandanteneinstellung nicht gefunden.",
        "errors.core.tenant.duplicate_code": "Mandantencode existiert bereits.",
        "errors.core.branch.duplicate_code": "Niederlassungscode existiert in diesem Mandanten bereits.",
        "errors.core.mandate.duplicate_code": "Mandatscode existiert in diesem Mandanten bereits.",
        "errors.core.setting.duplicate_key": "Einstellungsschluessel existiert fuer diesen Mandanten bereits.",
        "errors.core.setting.stale_version": "Die Einstellung wurde zwischenzeitlich geaendert.",
        "errors.core.branch.tenant_mismatch": "Die Niederlassung gehoert nicht zum angeforderten Mandanten.",
        "errors.core.mandate.tenant_mismatch": "Das Mandat gehoert nicht zum angeforderten Mandanten.",
        "errors.core.setting.tenant_mismatch": "Die Einstellung gehoert nicht zum angeforderten Mandanten.",
        "errors.core.mandate.invalid_branch_scope": "Die Mandatsniederlassung gehoert nicht zum Mandanten.",
        "errors.core.lifecycle.archived_record": "Archivierte Datensaetze koennen nicht reaktiviert werden.",
        "errors.core.conflict.integrity": "Die Core-Administrationsaenderung verletzt eine Integritaetsregel.",
        "errors.iam.auth.invalid_credentials": "Die Anmeldedaten sind ungueltig.",
        "errors.iam.auth.invalid_access_token": "Das Zugriffstoken ist ungueltig oder abgelaufen.",
        "errors.iam.auth.invalid_refresh_token": "Das Sitzungstoken ist ungueltig oder abgelaufen.",
        "errors.iam.auth.invalid_reset_token": "Das Passwort-Reset-Token ist ungueltig oder abgelaufen.",
        "errors.iam.auth.rate_limited": "Zu viele Anmeldeversuche. Bitte spaeter erneut versuchen.",
        "errors.iam.authorization.permission_denied": "Die benoetigte Berechtigung fehlt fuer diese Aktion.",
        "errors.iam.authorization.scope_denied": "Der Rollen-Scope erlaubt diesen Zugriff nicht.",
        "errors.docs.document.not_found": "Dokument nicht gefunden.",
        "errors.docs.document_type.not_found": "Dokumenttyp nicht gefunden.",
        "errors.docs.document.tenant_mismatch": "Das Dokument gehoert nicht zum angeforderten Mandanten.",
        "errors.docs.document_link.unsupported_owner_type": "Der Dokument-Linktyp wird nicht unterstuetzt.",
        "errors.docs.document_link.owner_not_found": "Das verknuepfte Zielelement wurde nicht gefunden.",
        "errors.docs.document_link.duplicate": "Diese Dokumentverknuepfung existiert bereits.",
        "errors.docs.document_version.invalid_content": "Der Dokumentinhalt ist ungueltig kodiert.",
        "errors.docs.document_version.not_found": "Dokumentversion nicht gefunden.",
        "errors.docs.storage.object_not_found": "Die gespeicherte Dokumentdatei wurde nicht gefunden.",
        "errors.comm.template.not_found": "Nachrichtenvorlage nicht gefunden.",
        "errors.comm.template.language_not_supported": "Die Sprachversion der Nachrichtenvorlage wird nicht unterstuetzt.",
        "errors.comm.message.not_found": "Ausgehende Nachricht nicht gefunden.",
        "errors.comm.attachment.document_not_found": "Angehaengtes Dokument nicht gefunden.",
        "errors.comm.delivery_attempt.recipient_not_found": "Nachrichtenempfaenger nicht gefunden.",
        "errors.comm.render.missing_placeholder": "Zum Rendern der Nachricht fehlen Platzhalterwerte.",
        "errors.info.notice.not_found": "Hinweis nicht gefunden.",
        "errors.info.notice.audience_missing": "Ein veroeffentlichter Hinweis benoetigt mindestens eine Zielgruppe.",
        "errors.info.notice.audience_kind_invalid": "Die Zielgruppenart fuer den Hinweis ist ungueltig.",
        "errors.info.notice.language_not_supported": "Die Hinweissprache wird nicht unterstuetzt.",
        "errors.info.notice_read.not_visible": "Dieser Hinweis ist fuer die aktuelle Rolle nicht sichtbar.",
        "errors.info.notice_read.already_acknowledged": "Der Hinweis wurde bereits bestaetigt.",
        "errors.info.notice_link.duplicate": "Dieser Hinweislink existiert bereits.",
        "errors.integration.endpoint.not_found": "Integrationsendpunkt nicht gefunden.",
        "errors.integration.job.not_found": "Import-/Export-Job nicht gefunden.",
        "errors.integration.outbox.not_found": "Outbox-Ereignis nicht gefunden.",
        "errors.integration.endpoint.duplicate_provider": "Der Provider-Endpunkt existiert bereits fuer diesen Mandanten.",
        "errors.integration.secret.invalid": "Die Integrationskonfiguration konnte nicht gesichert werden.",
        "errors.customers.customer.not_found": "Kunde nicht gefunden.",
        "errors.customers.contact.not_found": "Kundenkontakt nicht gefunden.",
        "errors.customers.customer_address.not_found": "Kundenadresse nicht gefunden.",
        "errors.customers.customer.tenant_mismatch": "Der Kunde gehoert nicht zum angeforderten Mandanten.",
        "errors.customers.contact.tenant_mismatch": "Der Kontakt gehoert nicht zum angeforderten Mandanten.",
        "errors.customers.contact.customer_mismatch": "Der Kontakt gehoert nicht zum angeforderten Kunden.",
        "errors.customers.customer_address.tenant_mismatch": "Die Kundenadresse gehoert nicht zum angeforderten Mandanten.",
        "errors.customers.customer_address.customer_mismatch": "Die Kundenadresse gehoert nicht zum angeforderten Kunden.",
        "errors.customers.customer.duplicate_number": "Die Kundennummer existiert in diesem Mandanten bereits.",
        "errors.customers.customer.stale_version": "Der Kunde wurde zwischenzeitlich geaendert.",
        "errors.customers.contact.stale_version": "Der Kundenkontakt wurde zwischenzeitlich geaendert.",
        "errors.customers.address_link.stale_version": "Die Kundenadresse wurde zwischenzeitlich geaendert.",
        "errors.customers.contact.duplicate_email": "Diese E-Mail-Adresse existiert fuer den Kunden bereits.",
        "errors.customers.contact.primary_conflict": "Es darf nur einen primaeren Kontakt pro Kunde geben.",
        "errors.customers.contact.duplicate_user_link": "Dieses Portal-Konto ist bereits einem anderen Kontakt zugeordnet.",
        "errors.customers.contact.invalid_user_scope": "Das verknuepfte Portal-Konto gehoert nicht zum Mandanten.",
        "errors.customers.customer_address.default_conflict": "Es darf nur eine Standardadresse pro Adresstyp geben.",
        "errors.customers.customer_address.duplicate_link": "Diese Kundenadressverknuepfung existiert bereits.",
        "errors.customers.customer_address.invalid_type": "Der Kundenadresstyp ist ungueltig.",
        "errors.customers.customer_address.address_not_found": "Die verknuepfte Adresse wurde nicht gefunden.",
        "errors.customers.lookup.not_found": "Der Lookup-Wert wurde nicht gefunden.",
        "errors.customers.lookup.invalid_domain": "Der Lookup-Wert gehoert nicht zur erwarteten Fachdomaeine.",
        "errors.customers.lookup.scope_mismatch": "Der Lookup-Wert gehoert zu einem anderen Mandanten.",
        "errors.customers.customer.invalid_branch_scope": "Die Standardniederlassung gehoert nicht zum Mandanten.",
        "errors.customers.customer.invalid_mandate_scope": "Das Standardmandat gehoert nicht zum Mandanten.",
        "errors.customers.customer.mandate_branch_mismatch": "Das Standardmandat gehoert nicht zur Standardniederlassung.",
        "errors.customers.lifecycle.archived_record": "Archivierte Kundendaten koennen nicht reaktiviert werden.",
        "errors.customers.lifecycle.invalid_archive_state": "Status und Archivierungszeitpunkt sind inkonsistent.",
        "errors.customers.conflict.integrity": "Die Kundenaenderung verletzt eine Integritaetsregel.",
        "errors.customers.import.invalid_content": "Die Importdatei ist kein gueltiges Base64-kodiertes CSV-Dokument.",
        "errors.customers.import.invalid_headers": "Die Importdatei enthaelt nicht die erwarteten Pflichtspalten.",
        "errors.customers.authorization.portal_forbidden": "Externe Portalrollen duerfen die interne Kundenverwaltung nicht direkt verwenden.",
        "errors.customers.authorization.internal_scope_required": "Die Kundenverwaltung erfordert einen internen Tenant-Scope.",
        "errors.customers.portal.scope_not_resolved": "Der Kunden-Scope fuer das Portal konnte nicht eindeutig aufgeloest werden.",
        "errors.customers.portal.contact_not_linked": "Dem aktuellen Portal-Konto ist kein aktiver Kundenkontakt zugeordnet.",
        "errors.customers.portal.contact_inactive": "Der verknuepfte Kundenkontakt ist deaktiviert oder archiviert.",
        "errors.customers.portal.customer_inactive": "Der verknuepfte Kunde ist deaktiviert oder archiviert.",
        "errors.customers.history_entry.not_found": "Der Historieneintrag wurde nicht gefunden.",
        "errors.customers.employee_block.not_found": "Die Kundensperre fuer Mitarbeitende wurde nicht gefunden.",
        "errors.customers.employee_block.invalid_employee_id": "Die Mitarbeitendenreferenz fuer die Kundensperre fehlt.",
        "errors.customers.employee_block.invalid_effective_range": "Der Sperrzeitraum ist ungueltig.",
        "errors.customers.employee_block.overlap": "Fuer diese Mitarbeitendenreferenz existiert bereits eine ueberlappende Kundensperre.",
        "errors.customers.employee_block.stale_version": "Die Kundensperre wurde zwischenzeitlich geaendert.",
        "errors.customers.billing_profile.not_found": "Kundenabrechnungsprofil nicht gefunden.",
        "errors.customers.billing_profile.duplicate_customer": "Fuer diesen Kunden existiert bereits ein Abrechnungsprofil.",
        "errors.customers.billing_profile.stale_version": "Das Abrechnungsprofil wurde zwischenzeitlich geaendert.",
        "errors.customers.billing_profile.tenant_mismatch": "Das Abrechnungsprofil gehoert nicht zum angeforderten Mandanten.",
        "errors.customers.billing_profile.customer_mismatch": "Das Abrechnungsprofil gehoert nicht zum angeforderten Kunden.",
        "errors.customers.billing_profile.invalid_invoice_email": "Die Rechnungs-E-Mail im Abrechnungsprofil ist ungueltig.",
        "errors.customers.billing_profile.invalid_payment_terms": "Die Zahlungsfrist ist ungueltig.",
        "errors.customers.billing_profile.tax_exemption_reason_required": "Bei Steuerbefreiung ist ein Grund erforderlich.",
        "errors.customers.billing_profile.tax_exemption_reason_forbidden": "Ein Steuerbefreiungsgrund darf nur bei aktiver Steuerbefreiung gesetzt werden.",
        "errors.customers.billing_profile.bank_account_holder_required": "Bei Bankdaten ist ein Kontoinhaber erforderlich.",
        "errors.customers.billing_profile.bank_iban_required": "Bei Bankdaten ist eine IBAN erforderlich.",
        "errors.customers.billing_profile.e_invoice_required": "Fuer E-Rechnungsversand muss E-Rechnung aktiviert sein.",
        "errors.customers.billing_profile.e_invoice_dispatch_mismatch": "Aktive E-Rechnung ist nur mit dem Versandweg E-Rechnung zulaessig.",
        "errors.customers.billing_profile.leitweg_required": "Fuer E-Rechnungsversand ist eine Leitweg-/Routing-ID erforderlich.",
        "errors.customers.billing_profile.leitweg_forbidden": "Eine Leitweg-/Routing-ID darf nur bei aktiver E-Rechnung gesetzt werden.",
        "errors.customers.billing_profile.dispatch_email_required": "Fuer E-Mail-PDF-Versand ist eine Rechnungs-E-Mail erforderlich.",
        "errors.customers.billing_profile.invoice_layout_incompatible": "Das gewaehlte Rechnungslayout ist mit dem Versandweg nicht kompatibel.",
        "errors.customers.invoice_party.not_found": "Rechnungspartei nicht gefunden.",
        "errors.customers.invoice_party.tenant_mismatch": "Die Rechnungspartei gehoert nicht zum angeforderten Mandanten.",
        "errors.customers.invoice_party.customer_mismatch": "Die Rechnungspartei gehoert nicht zum angeforderten Kunden.",
        "errors.customers.invoice_party.company_name_required": "Fuer die Rechnungspartei ist ein Firmenname erforderlich.",
        "errors.customers.invoice_party.address_not_found": "Die verknuepfte Rechnungsadresse wurde nicht gefunden.",
        "errors.customers.invoice_party.invalid_invoice_email": "Die Rechnungs-E-Mail der Rechnungspartei ist ungueltig.",
        "errors.customers.invoice_party.default_conflict": "Es darf nur eine Standard-Rechnungspartei pro Kunde geben.",
        "errors.customers.invoice_party.stale_version": "Die Rechnungspartei wurde zwischenzeitlich geaendert.",
        "errors.customers.rate_card.not_found": "Preiskarte nicht gefunden.",
        "errors.customers.rate_card.tenant_mismatch": "Die Preiskarte gehoert nicht zum angeforderten Mandanten.",
        "errors.customers.rate_card.customer_mismatch": "Die Preiskarte gehoert nicht zum angeforderten Kunden.",
        "errors.customers.rate_card.rate_kind_required": "Die Preiskartenart ist erforderlich.",
        "errors.customers.rate_card.invalid_currency": "Der Waehrungscode der Preiskarte ist ungueltig.",
        "errors.customers.rate_card.invalid_window": "Das Gueltigkeitsfenster der Preiskarte ist ungueltig.",
        "errors.customers.rate_card.overlap": "Die Preiskarte ueberschneidet sich mit einer bestehenden aktiven Karte gleicher Art.",
        "errors.customers.rate_card.stale_version": "Die Preiskarte wurde zwischenzeitlich geaendert.",
        "errors.customers.rate_line.not_found": "Preiszeile nicht gefunden.",
        "errors.customers.rate_line.tenant_mismatch": "Die Preiszeile gehoert nicht zum angeforderten Mandanten.",
        "errors.customers.rate_line.rate_card_mismatch": "Die Preiszeile gehoert nicht zur angeforderten Preiskarte.",
        "errors.customers.rate_line.line_kind_required": "Die Preiszeilenart ist erforderlich.",
        "errors.customers.rate_line.invalid_billing_unit": "Die Abrechnungseinheit der Preiszeile ist ungueltig.",
        "errors.customers.rate_line.invalid_unit_price": "Der Einzelpreis der Preiszeile ist ungueltig.",
        "errors.customers.rate_line.invalid_minimum_quantity": "Die Mindestmenge der Preiszeile ist ungueltig.",
        "errors.customers.rate_line.duplicate_dimension": "Diese Preisdimension existiert bereits auf der Preiskarte.",
        "errors.customers.rate_line.stale_version": "Die Preiszeile wurde zwischenzeitlich geaendert.",
        "errors.customers.surcharge_rule.not_found": "Zuschlagsregel nicht gefunden.",
        "errors.customers.surcharge_rule.tenant_mismatch": "Die Zuschlagsregel gehoert nicht zum angeforderten Mandanten.",
        "errors.customers.surcharge_rule.rate_card_mismatch": "Die Zuschlagsregel gehoert nicht zur angeforderten Preiskarte.",
        "errors.customers.surcharge_rule.surcharge_type_required": "Der Zuschlagstyp ist erforderlich.",
        "errors.customers.surcharge_rule.invalid_window": "Das Gueltigkeitsfenster der Zuschlagsregel ist ungueltig.",
        "errors.customers.surcharge_rule.outside_rate_card_window": "Die Zuschlagsregel muss innerhalb des Gueltigkeitsfensters der Preiskarte liegen.",
        "errors.customers.surcharge_rule.invalid_weekday_mask": "Die Wochentagsmaske der Zuschlagsregel ist ungueltig.",
        "errors.customers.surcharge_rule.invalid_time_range": "Das Zeitfenster der Zuschlagsregel ist ungueltig.",
        "errors.customers.surcharge_rule.invalid_amount_combination": "Es muss genau ein prozentualer oder fixer Zuschlagswert gesetzt sein.",
        "errors.customers.surcharge_rule.invalid_currency": "Die Waehrung der Zuschlagsregel ist ungueltig.",
        "errors.customers.surcharge_rule.stale_version": "Die Zuschlagsregel wurde zwischenzeitlich geaendert.",
        "errors.recruiting.applicant.tenant_not_found": "Das Bewerbungsformular wurde fuer diesen Mandanten nicht gefunden.",
        "errors.recruiting.applicant.form_disabled": "Das Bewerbungsformular ist derzeit nicht verfuegbar.",
        "errors.recruiting.applicant.origin_denied": "Diese Einbettungsherkunft ist fuer das Bewerbungsformular nicht freigegeben.",
        "errors.recruiting.applicant.rate_limited": "Zu viele Bewerbungen aus dieser Quelle. Bitte spaeter erneut versuchen.",
        "errors.recruiting.applicant.consent_required": "Die Datenschutz-Einwilligung muss vor dem Absenden bestaetigt werden.",
        "errors.recruiting.applicant.policy_mismatch": "Die angezeigte Datenschutzerklaerung ist nicht mehr aktuell. Bitte das Formular neu laden.",
        "errors.recruiting.applicant.field_required": "Ein Pflichtfeld im Bewerbungsformular fehlt.",
        "errors.recruiting.applicant.invalid_email": "Die angegebene E-Mail-Adresse ist ungueltig.",
        "errors.recruiting.applicant.invalid_field_option": "Eine ausgewaehlte Formularoption ist ungueltig.",
        "errors.recruiting.applicant.too_many_attachments": "Es wurden zu viele Anlagen hochgeladen.",
        "errors.recruiting.applicant.attachment_type_not_allowed": "Dieser Anhangstyp ist fuer das Bewerbungsformular nicht erlaubt.",
        "errors.recruiting.applicant.attachment_too_large": "Eine hochgeladene Datei ueberschreitet die zulaessige Groesse.",
        "errors.recruiting.applicant.duplicate_submission": "Diese Bewerbung wurde bereits uebermittelt.",
        "errors.recruiting.applicant.not_found": "Bewerbung nicht gefunden.",
        "errors.recruiting.applicant.invalid_status": "Der Bewerbungsstatus ist ungueltig.",
        "errors.recruiting.applicant.transition_not_allowed": "Dieser Statuswechsel ist fuer die Bewerbung nicht erlaubt.",
        "errors.recruiting.applicant.interview_time_required": "Fuer den Interviewstatus muss ein Termin hinterlegt werden.",
        "errors.recruiting.applicant.decision_reason_required": "Fuer diese Entscheidung ist eine Begruendung erforderlich.",
        "errors.recruiting.applicant.reopen_note_required": "Zum Wiederoeffnen der Bewerbung ist eine Notiz erforderlich.",
        "errors.recruiting.applicant.hiring_target_required": "Fuer die Uebergabe an die Konvertierung ist ein Einstellungsdatum erforderlich.",
        "errors.recruiting.applicant.note_required": "Fuer diese Aktivitaet ist eine Notiz erforderlich.",
        "errors.recruiting.applicant.invalid_activity_type": "Der Aktivitaetstyp fuer die Bewerbung ist ungueltig.",
        "errors.recruiting.applicant.scope_denied": "Der Recruiting-Scope erlaubt diesen Zugriff nicht.",
        "errors.recruiting.applicant.converted_employee_missing": "Die Bewerbungsumwandlung verweist auf eine fehlende Mitarbeitendenakte.",
        "errors.employees.employee.not_found": "Mitarbeitender nicht gefunden.",
        "errors.employees.employee.tenant_mismatch": "Der Mitarbeitende gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.employee.duplicate_personnel_no": "Die Personalnummer existiert in diesem Mandanten bereits.",
        "errors.employees.employee.duplicate_user_link": "Dieses Benutzerkonto ist bereits einem anderen Mitarbeitenden zugeordnet.",
        "errors.employees.employee.invalid_dates": "Ein Austrittsdatum darf nicht vor dem Eintrittsdatum liegen.",
        "errors.employees.employee.branch_not_found": "Die Standardniederlassung wurde nicht gefunden.",
        "errors.employees.employee.mandate_not_found": "Das Standardmandat wurde nicht gefunden.",
        "errors.employees.employee.mandate_branch_mismatch": "Das Standardmandat gehoert nicht zur Standardniederlassung.",
        "errors.employees.employee.stale_version": "Die Mitarbeitendenstammdaten wurden zwischenzeitlich geaendert.",
        "errors.employees.user.not_found": "Das verknuepfte Benutzerkonto wurde nicht gefunden.",
        "errors.employees.private_profile.not_found": "Das private Mitarbeitendenprofil wurde nicht gefunden.",
        "errors.employees.private_profile.tenant_mismatch": "Das private Mitarbeitendenprofil gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.private_profile.employee_mismatch": "Das private Mitarbeitendenprofil gehoert nicht zum angeforderten Mitarbeitenden.",
        "errors.employees.private_profile.stale_version": "Das private Mitarbeitendenprofil wurde zwischenzeitlich geaendert.",
        "errors.employees.address_history.not_found": "Der Mitarbeitendenadressverlauf wurde nicht gefunden.",
        "errors.employees.address_history.tenant_mismatch": "Der Mitarbeitendenadressverlauf gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.address_history.employee_mismatch": "Der Mitarbeitendenadressverlauf gehoert nicht zum angeforderten Mitarbeitenden.",
        "errors.employees.address_history.address_not_found": "Die verknuepfte Adresse wurde nicht gefunden.",
        "errors.employees.address_history.invalid_type": "Der Mitarbeitendenadresstyp ist ungueltig.",
        "errors.employees.address_history.invalid_window": "Das gueltige Adresszeitfenster ist ungueltig.",
        "errors.employees.address_history.overlap": "Fuer diesen Mitarbeitenden existiert bereits ein ueberlappendes Adresszeitfenster.",
        "errors.employees.address_history.stale_version": "Der Mitarbeitendenadressverlauf wurde zwischenzeitlich geaendert.",
        "errors.employees.group.not_found": "Die Mitarbeitendengruppe wurde nicht gefunden.",
        "errors.employees.group.tenant_mismatch": "Die Mitarbeitendengruppe gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.group.duplicate_code": "Der Gruppencode existiert in diesem Mandanten bereits.",
        "errors.employees.group.stale_version": "Die Mitarbeitendengruppe wurde zwischenzeitlich geaendert.",
        "errors.employees.group_member.not_found": "Die Gruppenzuordnung wurde nicht gefunden.",
        "errors.employees.group_member.tenant_mismatch": "Die Gruppenzuordnung gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.group_member.invalid_window": "Das Zeitfenster der Gruppenzuordnung ist ungueltig.",
        "errors.employees.group_member.stale_version": "Die Gruppenzuordnung wurde zwischenzeitlich geaendert.",
        "errors.employees.note.not_found": "Die Mitarbeitendennotiz wurde nicht gefunden.",
        "errors.employees.note.tenant_mismatch": "Die Mitarbeitendennotiz gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.note.employee_mismatch": "Die Mitarbeitendennotiz gehoert nicht zum angeforderten Mitarbeitenden.",
        "errors.employees.note.invalid_type": "Der Mitarbeitendennotiztyp ist ungueltig.",
        "errors.employees.note.reminder_date_required": "Fuer Erinnerungen ist ein Erinnerungsdatum erforderlich.",
        "errors.employees.note.invalid_completion": "Der Abschlussstatus der Mitarbeitendennotiz ist ungueltig.",
        "errors.employees.note.stale_version": "Die Mitarbeitendennotiz wurde zwischenzeitlich geaendert.",
        "errors.employees.function_type.not_found": "Der Funktionstyp wurde nicht gefunden.",
        "errors.employees.function_type.tenant_mismatch": "Der Funktionstyp gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.function_type.duplicate_code": "Der Funktionstyp-Code existiert in diesem Mandanten bereits.",
        "errors.employees.function_type.stale_version": "Der Funktionstyp wurde zwischenzeitlich geaendert.",
        "errors.employees.qualification_type.not_found": "Der Qualifikationstyp wurde nicht gefunden.",
        "errors.employees.qualification_type.tenant_mismatch": "Der Qualifikationstyp gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.qualification_type.duplicate_code": "Der Qualifikationstyp-Code existiert in diesem Mandanten bereits.",
        "errors.employees.qualification_type.invalid_validity_days": "Die Standardgueltigkeit muss groesser als null sein.",
        "errors.employees.qualification_type.stale_version": "Der Qualifikationstyp wurde zwischenzeitlich geaendert.",
        "errors.employees.employee_qualification.not_found": "Die Mitarbeitendenqualifikation wurde nicht gefunden.",
        "errors.employees.employee_qualification.tenant_mismatch": "Die Mitarbeitendenqualifikation gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.employee_qualification.invalid_kind": "Die Qualifikationsart ist ungueltig.",
        "errors.employees.employee_qualification.target_mismatch": "Funktion und Qualifikation passen nicht zur gewaehlten Qualifikationsart.",
        "errors.employees.employee_qualification.invalid_window": "Das Gueltigkeitsfenster der Mitarbeitendenqualifikation ist ungueltig.",
        "errors.employees.employee_qualification.expiry_required": "Fuer diesen Qualifikationstyp ist ein Ablaufdatum erforderlich.",
        "errors.employees.employee_qualification.stale_version": "Die Mitarbeitendenqualifikation wurde zwischenzeitlich geaendert.",
        "errors.employees.availability_rule.not_found": "Die Verfuegbarkeitsregel wurde nicht gefunden.",
        "errors.employees.availability_rule.tenant_mismatch": "Die Verfuegbarkeitsregel gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.availability_rule.invalid_kind": "Die Art der Verfuegbarkeitsregel ist ungueltig.",
        "errors.employees.availability_rule.invalid_window": "Das Zeitfenster der Verfuegbarkeitsregel ist ungueltig.",
        "errors.employees.availability_rule.invalid_recurrence": "Die Wiederholungsart der Verfuegbarkeitsregel ist ungueltig.",
        "errors.employees.availability_rule.invalid_recurrence_mask": "Die Wochentagsmaske der Verfuegbarkeitsregel ist ungueltig.",
        "errors.employees.availability_rule.stale_version": "Die Verfuegbarkeitsregel wurde zwischenzeitlich geaendert.",
        "errors.employees.absence.not_found": "Die Abwesenheit wurde nicht gefunden.",
        "errors.employees.absence.tenant_mismatch": "Die Abwesenheit gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.absence.invalid_type": "Die Abwesenheitsart ist ungueltig.",
        "errors.employees.absence.invalid_window": "Das Abwesenheitszeitfenster ist ungueltig.",
        "errors.employees.absence.overlap": "Fuer diesen Mitarbeitenden existiert bereits eine ueberlappende aktive Abwesenheit.",
        "errors.employees.absence.stale_version": "Die Abwesenheit wurde zwischenzeitlich geaendert.",
        "errors.employees.leave_balance.not_found": "Der Urlaubsstand wurde nicht gefunden.",
        "errors.employees.leave_balance.tenant_mismatch": "Der Urlaubsstand gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.leave_balance.invalid_year": "Das Urlaubsjahr ist ungueltig.",
        "errors.employees.event_application.not_found": "Die Event-Bewerbung wurde nicht gefunden.",
        "errors.employees.event_application.tenant_mismatch": "Die Event-Bewerbung gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.event_application.planning_record_required": "Ein Planungsdatensatz ist fuer die Event-Bewerbung erforderlich.",
        "errors.employees.event_application.invalid_status": "Der Status der Event-Bewerbung ist ungueltig.",
        "errors.employees.event_application.duplicate": "Fuer diesen Mitarbeitenden existiert bereits eine Bewerbung auf diesen Planungsdatensatz.",
        "errors.employees.time_account.not_found": "Das Zeitkonto wurde nicht gefunden.",
        "errors.employees.time_account.tenant_mismatch": "Das Zeitkonto gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.time_account.invalid_type": "Die Zeitkontoart ist ungueltig.",
        "errors.employees.time_account.duplicate": "Diese Zeitkontoart existiert fuer den Mitarbeitenden bereits.",
        "errors.employees.time_account_txn.tenant_mismatch": "Die Zeitkontobuchung gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.time_account_txn.invalid_type": "Die Art der Zeitkontobuchung ist ungueltig.",
        "errors.employees.allowance.not_found": "Die Zulage wurde nicht gefunden.",
        "errors.employees.allowance.tenant_mismatch": "Die Zulage gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.allowance.invalid_window": "Das Gueltigkeitsfenster der Zulage ist ungueltig.",
        "errors.employees.allowance.overlap": "Fuer diese Zulagenbasis existiert bereits eine ueberlappende Regel.",
        "errors.employees.allowance.stale_version": "Die Zulage wurde zwischenzeitlich geaendert.",
        "errors.employees.advance.not_found": "Der Vorschuss wurde nicht gefunden.",
        "errors.employees.advance.tenant_mismatch": "Der Vorschuss gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.advance.duplicate_no": "Die Vorschussnummer existiert in diesem Mandanten bereits.",
        "errors.employees.advance.invalid_status": "Der Vorschussstatus ist ungueltig.",
        "errors.employees.advance.stale_version": "Der Vorschuss wurde zwischenzeitlich geaendert.",
        "errors.employees.credential.not_found": "Die ID-Kennung wurde nicht gefunden.",
        "errors.employees.credential.tenant_mismatch": "Die ID-Kennung gehoert nicht zum angeforderten Mandanten.",
        "errors.employees.credential.invalid_type": "Die Art der ID-Kennung ist ungueltig.",
        "errors.employees.credential.invalid_status": "Der Status der ID-Kennung ist ungueltig.",
        "errors.employees.credential.invalid_window": "Das Gueltigkeitsfenster der ID-Kennung ist ungueltig.",
        "errors.employees.credential.duplicate_no": "Die Ausweisnummer existiert in diesem Mandanten bereits.",
        "errors.employees.credential.duplicate_encoded_value": "Der kodierte Kennungswert existiert in diesem Mandanten bereits.",
        "errors.employees.credential.stale_version": "Die ID-Kennung wurde zwischenzeitlich geaendert.",
        "errors.employees.self_service.employee_not_found": "Die eigene Mitarbeitendenzuordnung wurde nicht gefunden.",
        "errors.employees.self_service.address.invalid_effective_date": "Das Startdatum fuer die Adressaenderung ist ungueltig.",
        "errors.employees.self_service.availability_rule.invalid_kind": "Diese Regelart ist in der Selbstbedienung nicht erlaubt.",
        "errors.employees.self_service.availability_rule.not_found": "Die eigene Verfuegbarkeitsregel wurde nicht gefunden.",
        "errors.employees.self_service.event_application.not_found": "Die eigene Bewerbung wurde nicht gefunden.",
        "errors.employees.photo.write_failed": "Das Profilfoto konnte nicht gespeichert werden.",
        "errors.employees.import.invalid_csv": "Die Importdatei konnte nicht gelesen werden.",
        "errors.employees.import.invalid_headers": "Die Importdatei verwendet ein ungueltiges Spaltenlayout.",
        "errors.employees.access.username_taken": "Der Benutzername ist in diesem Mandanten bereits vergeben.",
        "errors.employees.access.email_taken": "Die E-Mail-Adresse ist in diesem Mandanten bereits vergeben.",
        "errors.employees.access.ambiguous_match": "Fuer die Benutzerverknuepfung muss genau ein Suchkriterium angegeben werden.",
        "errors.employees.access.role_missing": "Die Rolle fuer Mitarbeitendenzugang ist nicht im IAM-Katalog verfuegbar.",
        "messages.iam.auth.logout_success": "Die Sitzung wurde erfolgreich beendet.",
        "messages.iam.auth.password_reset_requested":
            "Wenn ein passendes Konto existiert, wurde ein Reset-Vorgang gestartet.",
        "messages.iam.auth.password_reset_confirmed":
            "Das Passwort wurde erfolgreich zurueckgesetzt.",
    },
    "en": {
        "errors.platform.internal": "An internal platform error has occurred.",
        "errors.platform.database_unavailable": "The database is currently unavailable.",
        "errors.core.authorization.forbidden": "Access to this core administration action is not allowed.",
        "errors.core.tenant.not_found": "Tenant not found.",
        "errors.core.branch.not_found": "Branch not found.",
        "errors.core.mandate.not_found": "Mandate not found.",
        "errors.core.tenant_setting.not_found": "Tenant setting not found.",
        "errors.core.tenant.duplicate_code": "Tenant code already exists.",
        "errors.core.branch.duplicate_code": "Branch code already exists in this tenant.",
        "errors.core.mandate.duplicate_code": "Mandate code already exists in this tenant.",
        "errors.core.setting.duplicate_key": "Setting key already exists for this tenant.",
        "errors.core.setting.stale_version": "The setting was changed by another update.",
        "errors.core.branch.tenant_mismatch": "The branch does not belong to the requested tenant.",
        "errors.core.mandate.tenant_mismatch": "The mandate does not belong to the requested tenant.",
        "errors.core.setting.tenant_mismatch": "The setting does not belong to the requested tenant.",
        "errors.core.mandate.invalid_branch_scope": "The mandate branch does not belong to the tenant.",
        "errors.core.lifecycle.archived_record": "Archived records cannot be reactivated.",
        "errors.core.conflict.integrity": "The core administration change violates an integrity rule.",
        "errors.iam.auth.invalid_credentials": "The login credentials are invalid.",
        "errors.iam.auth.invalid_access_token": "The access token is invalid or expired.",
        "errors.iam.auth.invalid_refresh_token": "The session token is invalid or expired.",
        "errors.iam.auth.invalid_reset_token": "The password reset token is invalid or expired.",
        "errors.iam.auth.rate_limited": "Too many login attempts. Please try again later.",
        "errors.iam.authorization.permission_denied": "The required permission for this action is missing.",
        "errors.iam.authorization.scope_denied": "The assigned role scope does not allow this access.",
        "errors.docs.document.not_found": "Document not found.",
        "errors.docs.document_type.not_found": "Document type not found.",
        "errors.docs.document.tenant_mismatch": "The document does not belong to the requested tenant.",
        "errors.docs.document_link.unsupported_owner_type": "The document link owner type is not supported.",
        "errors.docs.document_link.owner_not_found": "The linked owner record was not found.",
        "errors.docs.document_link.duplicate": "This document link already exists.",
        "errors.docs.document_version.invalid_content": "The document content encoding is invalid.",
        "errors.docs.document_version.not_found": "Document version not found.",
        "errors.docs.storage.object_not_found": "The stored document file was not found.",
        "errors.comm.template.not_found": "Message template not found.",
        "errors.comm.template.language_not_supported": "The message-template language is not supported.",
        "errors.comm.message.not_found": "Outbound message not found.",
        "errors.comm.attachment.document_not_found": "Attached document not found.",
        "errors.comm.delivery_attempt.recipient_not_found": "Message recipient not found.",
        "errors.comm.render.missing_placeholder": "Placeholder values are missing for message rendering.",
        "errors.info.notice.not_found": "Notice not found.",
        "errors.info.notice.audience_missing": "A published notice requires at least one audience.",
        "errors.info.notice.audience_kind_invalid": "The notice audience kind is invalid.",
        "errors.info.notice.language_not_supported": "The notice language is not supported.",
        "errors.info.notice_read.not_visible": "This notice is not visible for the current role scope.",
        "errors.info.notice_read.already_acknowledged": "The notice has already been acknowledged.",
        "errors.info.notice_link.duplicate": "This curated notice link already exists.",
        "errors.integration.endpoint.not_found": "Integration endpoint not found.",
        "errors.integration.job.not_found": "Import/export job not found.",
        "errors.integration.outbox.not_found": "Outbox event not found.",
        "errors.integration.endpoint.duplicate_provider": "The provider endpoint already exists for this tenant.",
        "errors.integration.secret.invalid": "The integration configuration could not be secured.",
        "errors.customers.customer.not_found": "Customer not found.",
        "errors.customers.contact.not_found": "Customer contact not found.",
        "errors.customers.customer_address.not_found": "Customer address link not found.",
        "errors.customers.customer.tenant_mismatch": "The customer does not belong to the requested tenant.",
        "errors.customers.contact.tenant_mismatch": "The contact does not belong to the requested tenant.",
        "errors.customers.contact.customer_mismatch": "The contact does not belong to the requested customer.",
        "errors.customers.customer_address.tenant_mismatch": "The customer address does not belong to the requested tenant.",
        "errors.customers.customer_address.customer_mismatch": "The customer address does not belong to the requested customer.",
        "errors.customers.customer.duplicate_number": "The customer number already exists in this tenant.",
        "errors.customers.customer.stale_version": "The customer was changed by another update.",
        "errors.customers.contact.stale_version": "The customer contact was changed by another update.",
        "errors.customers.address_link.stale_version": "The customer address link was changed by another update.",
        "errors.customers.contact.duplicate_email": "This email address already exists for the customer.",
        "errors.customers.contact.primary_conflict": "Only one primary contact is allowed per customer.",
        "errors.customers.contact.duplicate_user_link": "This portal account is already linked to another contact.",
        "errors.customers.contact.invalid_user_scope": "The linked portal account does not belong to this tenant.",
        "errors.customers.customer_address.default_conflict": "Only one default address is allowed per address type.",
        "errors.customers.customer_address.duplicate_link": "This customer-address link already exists.",
        "errors.customers.customer_address.invalid_type": "The customer-address type is invalid.",
        "errors.customers.customer_address.address_not_found": "The linked address was not found.",
        "errors.customers.lookup.not_found": "The lookup value was not found.",
        "errors.customers.lookup.invalid_domain": "The lookup value does not belong to the expected business domain.",
        "errors.customers.lookup.scope_mismatch": "The lookup value belongs to a different tenant.",
        "errors.customers.customer.invalid_branch_scope": "The default branch does not belong to this tenant.",
        "errors.customers.customer.invalid_mandate_scope": "The default mandate does not belong to this tenant.",
        "errors.customers.customer.mandate_branch_mismatch": "The default mandate does not belong to the default branch.",
        "errors.customers.lifecycle.archived_record": "Archived customer records cannot be reactivated.",
        "errors.customers.lifecycle.invalid_archive_state": "Status and archive timestamp are inconsistent.",
        "errors.customers.conflict.integrity": "The customer change violates an integrity rule.",
        "errors.customers.import.invalid_content": "The import file is not a valid base64-encoded CSV document.",
        "errors.customers.import.invalid_headers": "The import file does not contain the required columns.",
        "errors.customers.authorization.portal_forbidden": "External portal roles cannot use the internal customer administration API directly.",
        "errors.customers.authorization.internal_scope_required": "Customer administration requires an internal tenant scope.",
        "errors.customers.portal.scope_not_resolved": "The portal customer scope could not be resolved unambiguously.",
        "errors.customers.portal.contact_not_linked": "No active customer contact is linked to the current portal account.",
        "errors.customers.portal.contact_inactive": "The linked customer contact is inactive or archived.",
        "errors.customers.portal.customer_inactive": "The linked customer is inactive or archived.",
        "errors.customers.history_entry.not_found": "The history entry was not found.",
        "errors.customers.employee_block.not_found": "The customer employee block was not found.",
        "errors.customers.employee_block.invalid_employee_id": "The employee reference for the customer block is missing.",
        "errors.customers.employee_block.invalid_effective_range": "The block effective-date range is invalid.",
        "errors.customers.employee_block.overlap": "An overlapping customer block already exists for this employee reference.",
        "errors.customers.employee_block.stale_version": "The customer block was changed by another update.",
        "errors.customers.billing_profile.not_found": "Customer billing profile not found.",
        "errors.customers.billing_profile.duplicate_customer": "A billing profile already exists for this customer.",
        "errors.customers.billing_profile.stale_version": "The billing profile was changed by another update.",
        "errors.customers.billing_profile.tenant_mismatch": "The billing profile does not belong to the requested tenant.",
        "errors.customers.billing_profile.customer_mismatch": "The billing profile does not belong to the requested customer.",
        "errors.customers.billing_profile.invalid_invoice_email": "The billing-profile invoice email is invalid.",
        "errors.customers.billing_profile.invalid_payment_terms": "The payment term value is invalid.",
        "errors.customers.billing_profile.tax_exemption_reason_required": "A tax-exemption reason is required when tax exemption is enabled.",
        "errors.customers.billing_profile.tax_exemption_reason_forbidden": "A tax-exemption reason may only be set when tax exemption is enabled.",
        "errors.customers.billing_profile.bank_account_holder_required": "A bank account holder is required when bank data is stored.",
        "errors.customers.billing_profile.bank_iban_required": "An IBAN is required when bank data is stored.",
        "errors.customers.billing_profile.e_invoice_required": "E-invoice dispatch requires e-invoice to be enabled.",
        "errors.customers.billing_profile.e_invoice_dispatch_mismatch": "Active e-invoicing is only allowed with the e-invoice dispatch method.",
        "errors.customers.billing_profile.leitweg_required": "E-invoice dispatch requires a Leitweg/routing ID.",
        "errors.customers.billing_profile.leitweg_forbidden": "A Leitweg/routing ID may only be set when e-invoicing is enabled.",
        "errors.customers.billing_profile.dispatch_email_required": "Email-PDF dispatch requires an invoice email address.",
        "errors.customers.billing_profile.invoice_layout_incompatible": "The selected invoice layout is incompatible with the dispatch method.",
        "errors.customers.invoice_party.not_found": "Customer invoice party not found.",
        "errors.customers.invoice_party.tenant_mismatch": "The invoice party does not belong to the requested tenant.",
        "errors.customers.invoice_party.customer_mismatch": "The invoice party does not belong to the requested customer.",
        "errors.customers.invoice_party.company_name_required": "An invoice party requires a company name.",
        "errors.customers.invoice_party.address_not_found": "The linked invoice-party address was not found.",
        "errors.customers.invoice_party.invalid_invoice_email": "The invoice-party invoice email is invalid.",
        "errors.customers.invoice_party.default_conflict": "Only one default invoice party is allowed per customer.",
        "errors.customers.invoice_party.stale_version": "The invoice party was changed by another update.",
        "errors.customers.rate_card.not_found": "Customer rate card not found.",
        "errors.customers.rate_card.tenant_mismatch": "The rate card does not belong to the requested tenant.",
        "errors.customers.rate_card.customer_mismatch": "The rate card does not belong to the requested customer.",
        "errors.customers.rate_card.rate_kind_required": "A rate-card kind is required.",
        "errors.customers.rate_card.invalid_currency": "The rate-card currency code is invalid.",
        "errors.customers.rate_card.invalid_window": "The rate-card effective window is invalid.",
        "errors.customers.rate_card.overlap": "The rate card overlaps an existing active card of the same kind.",
        "errors.customers.rate_card.stale_version": "The rate card was changed by another update.",
        "errors.customers.rate_line.not_found": "Customer rate line not found.",
        "errors.customers.rate_line.tenant_mismatch": "The rate line does not belong to the requested tenant.",
        "errors.customers.rate_line.rate_card_mismatch": "The rate line does not belong to the requested rate card.",
        "errors.customers.rate_line.line_kind_required": "A rate-line kind is required.",
        "errors.customers.rate_line.invalid_billing_unit": "The rate-line billing unit is invalid.",
        "errors.customers.rate_line.invalid_unit_price": "The rate-line unit price is invalid.",
        "errors.customers.rate_line.invalid_minimum_quantity": "The rate-line minimum quantity is invalid.",
        "errors.customers.rate_line.duplicate_dimension": "This pricing dimension already exists on the rate card.",
        "errors.customers.rate_line.stale_version": "The rate line was changed by another update.",
        "errors.customers.surcharge_rule.not_found": "Customer surcharge rule not found.",
        "errors.customers.surcharge_rule.tenant_mismatch": "The surcharge rule does not belong to the requested tenant.",
        "errors.customers.surcharge_rule.rate_card_mismatch": "The surcharge rule does not belong to the requested rate card.",
        "errors.customers.surcharge_rule.surcharge_type_required": "A surcharge type is required.",
        "errors.customers.surcharge_rule.invalid_window": "The surcharge-rule effective window is invalid.",
        "errors.customers.surcharge_rule.outside_rate_card_window": "The surcharge rule must stay within the rate-card window.",
        "errors.customers.surcharge_rule.invalid_weekday_mask": "The surcharge-rule weekday mask is invalid.",
        "errors.customers.surcharge_rule.invalid_time_range": "The surcharge-rule time range is invalid.",
        "errors.customers.surcharge_rule.invalid_amount_combination": "Exactly one percentage or fixed amount must be set.",
        "errors.customers.surcharge_rule.invalid_currency": "The surcharge-rule currency is invalid.",
        "errors.customers.surcharge_rule.stale_version": "The surcharge rule was changed by another update.",
        "errors.recruiting.applicant.tenant_not_found": "The applicant form was not found for this tenant.",
        "errors.recruiting.applicant.form_disabled": "The applicant form is currently unavailable.",
        "errors.recruiting.applicant.origin_denied": "This embedding origin is not allowed for the applicant form.",
        "errors.recruiting.applicant.rate_limited": "Too many submissions came from this source. Please try again later.",
        "errors.recruiting.applicant.consent_required": "GDPR consent must be confirmed before submission.",
        "errors.recruiting.applicant.policy_mismatch": "The displayed privacy policy is outdated. Please reload the form.",
        "errors.recruiting.applicant.field_required": "A required applicant-form field is missing.",
        "errors.recruiting.applicant.invalid_email": "The provided email address is invalid.",
        "errors.recruiting.applicant.invalid_field_option": "A selected applicant-form option is invalid.",
        "errors.recruiting.applicant.too_many_attachments": "Too many attachments were uploaded.",
        "errors.recruiting.applicant.attachment_type_not_allowed": "This attachment type is not allowed for the applicant form.",
        "errors.recruiting.applicant.attachment_too_large": "An uploaded file exceeds the allowed size.",
        "errors.recruiting.applicant.duplicate_submission": "This application was already submitted.",
        "errors.recruiting.applicant.not_found": "Applicant not found.",
        "errors.recruiting.applicant.invalid_status": "The applicant status is invalid.",
        "errors.recruiting.applicant.transition_not_allowed": "This status transition is not allowed for the applicant.",
        "errors.recruiting.applicant.interview_time_required": "An interview appointment is required for the interview status.",
        "errors.recruiting.applicant.decision_reason_required": "A rationale is required for this decision.",
        "errors.recruiting.applicant.reopen_note_required": "A note is required to reopen this applicant.",
        "errors.recruiting.applicant.hiring_target_required": "A target hire date is required before marking the applicant ready for conversion.",
        "errors.recruiting.applicant.note_required": "A note is required for this activity.",
        "errors.recruiting.applicant.invalid_activity_type": "The applicant activity type is invalid.",
        "errors.recruiting.applicant.scope_denied": "The recruiting scope does not allow this access.",
        "errors.recruiting.applicant.converted_employee_missing": "The applicant conversion points to a missing employee record.",
        "errors.employees.employee.not_found": "Employee not found.",
        "errors.employees.employee.tenant_mismatch": "The employee does not belong to the requested tenant.",
        "errors.employees.employee.duplicate_personnel_no": "The personnel number already exists in this tenant.",
        "errors.employees.employee.duplicate_user_link": "This user account is already linked to another employee.",
        "errors.employees.employee.invalid_dates": "A termination date cannot be earlier than the hire date.",
        "errors.employees.employee.branch_not_found": "The default branch was not found.",
        "errors.employees.employee.mandate_not_found": "The default mandate was not found.",
        "errors.employees.employee.mandate_branch_mismatch": "The default mandate does not belong to the default branch.",
        "errors.employees.employee.stale_version": "The employee master record was changed by another update.",
        "errors.employees.user.not_found": "The linked user account was not found.",
        "errors.employees.private_profile.not_found": "The private employee profile was not found.",
        "errors.employees.private_profile.tenant_mismatch": "The private employee profile does not belong to the requested tenant.",
        "errors.employees.private_profile.employee_mismatch": "The private employee profile does not belong to the requested employee.",
        "errors.employees.private_profile.stale_version": "The private employee profile was changed by another update.",
        "errors.employees.address_history.not_found": "The employee address history record was not found.",
        "errors.employees.address_history.tenant_mismatch": "The employee address history does not belong to the requested tenant.",
        "errors.employees.address_history.employee_mismatch": "The employee address history does not belong to the requested employee.",
        "errors.employees.address_history.address_not_found": "The linked address was not found.",
        "errors.employees.address_history.invalid_type": "The employee address type is invalid.",
        "errors.employees.address_history.invalid_window": "The employee address validity window is invalid.",
        "errors.employees.address_history.overlap": "An overlapping address validity window already exists for this employee.",
        "errors.employees.address_history.stale_version": "The employee address history was changed by another update.",
        "errors.employees.group.not_found": "The employee group was not found.",
        "errors.employees.group.tenant_mismatch": "The employee group does not belong to the requested tenant.",
        "errors.employees.group.duplicate_code": "The employee-group code already exists in this tenant.",
        "errors.employees.group.stale_version": "The employee group was changed by another update.",
        "errors.employees.group_member.not_found": "The employee group assignment was not found.",
        "errors.employees.group_member.tenant_mismatch": "The employee group assignment does not belong to the requested tenant.",
        "errors.employees.group_member.invalid_window": "The employee group-assignment window is invalid.",
        "errors.employees.group_member.stale_version": "The employee group assignment was changed by another update.",
        "errors.employees.note.not_found": "The employee note was not found.",
        "errors.employees.note.tenant_mismatch": "The employee note does not belong to the requested tenant.",
        "errors.employees.note.employee_mismatch": "The employee note does not belong to the requested employee.",
        "errors.employees.note.invalid_type": "The employee note type is invalid.",
        "errors.employees.note.reminder_date_required": "A reminder date is required for reminder notes.",
        "errors.employees.note.invalid_completion": "The employee-note completion state is invalid.",
        "errors.employees.note.stale_version": "The employee note was changed by another update.",
        "errors.employees.function_type.not_found": "The function type was not found.",
        "errors.employees.function_type.tenant_mismatch": "The function type does not belong to the requested tenant.",
        "errors.employees.function_type.duplicate_code": "The function-type code already exists in this tenant.",
        "errors.employees.function_type.stale_version": "The function type was changed by another update.",
        "errors.employees.qualification_type.not_found": "The qualification type was not found.",
        "errors.employees.qualification_type.tenant_mismatch": "The qualification type does not belong to the requested tenant.",
        "errors.employees.qualification_type.duplicate_code": "The qualification-type code already exists in this tenant.",
        "errors.employees.qualification_type.invalid_validity_days": "The default validity must be greater than zero.",
        "errors.employees.qualification_type.stale_version": "The qualification type was changed by another update.",
        "errors.employees.employee_qualification.not_found": "The employee qualification was not found.",
        "errors.employees.employee_qualification.tenant_mismatch": "The employee qualification does not belong to the requested tenant.",
        "errors.employees.employee_qualification.invalid_kind": "The employee qualification kind is invalid.",
        "errors.employees.employee_qualification.target_mismatch": "The selected function and qualification targets do not match the qualification kind.",
        "errors.employees.employee_qualification.invalid_window": "The employee qualification validity window is invalid.",
        "errors.employees.employee_qualification.expiry_required": "An expiry date is required for this qualification type.",
        "errors.employees.employee_qualification.stale_version": "The employee qualification was changed by another update.",
        "errors.employees.availability_rule.not_found": "The availability rule was not found.",
        "errors.employees.availability_rule.tenant_mismatch": "The availability rule does not belong to the requested tenant.",
        "errors.employees.availability_rule.invalid_kind": "The availability-rule kind is invalid.",
        "errors.employees.availability_rule.invalid_window": "The availability-rule window is invalid.",
        "errors.employees.availability_rule.invalid_recurrence": "The availability-rule recurrence type is invalid.",
        "errors.employees.availability_rule.invalid_recurrence_mask": "The availability-rule weekday mask is invalid.",
        "errors.employees.availability_rule.stale_version": "The availability rule was changed by another update.",
        "errors.employees.absence.not_found": "The absence record was not found.",
        "errors.employees.absence.tenant_mismatch": "The absence does not belong to the requested tenant.",
        "errors.employees.absence.invalid_type": "The absence type is invalid.",
        "errors.employees.absence.invalid_window": "The absence window is invalid.",
        "errors.employees.absence.overlap": "An overlapping active absence already exists for this employee.",
        "errors.employees.absence.stale_version": "The absence was changed by another update.",
        "errors.employees.leave_balance.not_found": "The leave balance was not found.",
        "errors.employees.leave_balance.tenant_mismatch": "The leave balance does not belong to the requested tenant.",
        "errors.employees.leave_balance.invalid_year": "The leave-balance year is invalid.",
        "errors.employees.event_application.not_found": "The event application was not found.",
        "errors.employees.event_application.tenant_mismatch": "The event application does not belong to the requested tenant.",
        "errors.employees.event_application.planning_record_required": "A planning record is required for the event application.",
        "errors.employees.event_application.invalid_status": "The event-application status is invalid.",
        "errors.employees.event_application.duplicate": "An event application already exists for this employee and planning record.",
        "errors.employees.time_account.not_found": "The time account was not found.",
        "errors.employees.time_account.tenant_mismatch": "The time account does not belong to the requested tenant.",
        "errors.employees.time_account.invalid_type": "The time-account type is invalid.",
        "errors.employees.time_account.duplicate": "This time-account type already exists for the employee.",
        "errors.employees.time_account_txn.tenant_mismatch": "The time-account transaction does not belong to the requested tenant.",
        "errors.employees.time_account_txn.invalid_type": "The time-account transaction type is invalid.",
        "errors.employees.allowance.not_found": "The allowance was not found.",
        "errors.employees.allowance.tenant_mismatch": "The allowance does not belong to the requested tenant.",
        "errors.employees.allowance.invalid_window": "The allowance validity window is invalid.",
        "errors.employees.allowance.overlap": "An overlapping allowance already exists for this allowance basis.",
        "errors.employees.allowance.stale_version": "The allowance was changed by another update.",
        "errors.employees.advance.not_found": "The advance was not found.",
        "errors.employees.advance.tenant_mismatch": "The advance does not belong to the requested tenant.",
        "errors.employees.advance.duplicate_no": "The advance number already exists in this tenant.",
        "errors.employees.advance.invalid_status": "The advance status is invalid.",
        "errors.employees.advance.stale_version": "The advance was changed by another update.",
        "errors.employees.credential.not_found": "The ID credential was not found.",
        "errors.employees.credential.tenant_mismatch": "The ID credential does not belong to the requested tenant.",
        "errors.employees.credential.invalid_type": "The ID credential type is invalid.",
        "errors.employees.credential.invalid_status": "The ID credential status is invalid.",
        "errors.employees.credential.invalid_window": "The ID credential validity window is invalid.",
        "errors.employees.credential.duplicate_no": "The credential number already exists in this tenant.",
        "errors.employees.credential.duplicate_encoded_value": "The encoded credential value already exists in this tenant.",
        "errors.employees.credential.stale_version": "The ID credential was changed by another update.",
        "errors.employees.self_service.employee_not_found": "The linked employee self-service context was not found.",
        "errors.employees.self_service.address.invalid_effective_date": "The effective date for the address change is invalid.",
        "errors.employees.self_service.availability_rule.invalid_kind": "This rule kind is not allowed in self-service.",
        "errors.employees.self_service.availability_rule.not_found": "The self-service availability rule was not found.",
        "errors.employees.self_service.event_application.not_found": "The self-service event application was not found.",
        "errors.employees.photo.write_failed": "The profile photo could not be stored.",
        "errors.employees.import.invalid_csv": "The import file could not be read.",
        "errors.employees.import.invalid_headers": "The import file uses an invalid column layout.",
        "errors.employees.access.username_taken": "The username is already used in this tenant.",
        "errors.employees.access.email_taken": "The email address is already used in this tenant.",
        "errors.employees.access.ambiguous_match": "Exactly one user lookup field must be provided for employee access linkage.",
        "errors.employees.access.role_missing": "The employee access role is not available in the IAM catalog.",
        "messages.iam.auth.logout_success": "The session has been terminated successfully.",
        "messages.iam.auth.password_reset_requested":
            "If a matching account exists, a reset flow has been started.",
        "messages.iam.auth.password_reset_confirmed":
            "The password has been reset successfully.",
    },
}


def translate_message(message_key: str, locale: str = DEFAULT_LOCALE) -> str:
    """Return a localized message for known API message keys."""

    normalized = locale.split("-")[0].lower()
    catalog = MESSAGES.get(normalized, MESSAGES[FALLBACK_LOCALE])
    fallback_catalog = MESSAGES[FALLBACK_LOCALE]
    return catalog.get(message_key) or fallback_catalog.get(message_key) or message_key
